name: Cargo Machete

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]

jobs:
  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
      - name: Install Machete
        run: cargo install cargo-machete --locked
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Machete
        run: cargo machete
