name: Cargo Machete

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]

jobs:
  cargo-machete:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85
      # Install with 1.85
      - name: Machete install
        run: cargo install cargo-machete --locked
      # Checkout will downgrade to 1.81
      - name: Checkout
        uses: actions/checkout@v4
      - name: Machete Check
        run: cargo machete
