# Copied from https://github.com/rerun-io/rerun_template
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize ]

name: Link checker

jobs:
  linkinator:
    name: linkinator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jprochazk/linkinator-action@main
        with:
          linksToSkip: "https://crates.io/crates/.*, http://localhost:.*" # Avoid crates.io rate-limiting
          retry: true
          retryErrors: true
          retryErrorsCount: 5
          retryErrorsJitter: 2000